import pytest

from dubstub.config import Config
from dubstub.evaluate.gen_pyright import normalize

TEST_FILE_1 = '''
"""
This type stub file was generated by pyright.
"""

import foo

"""
original docstring
"""

def foo():
    ...

# foo

# bar
'''

TEST_FILE_NORMALIZED_1 = '''
"""
original docstring
"""

import foo

def foo():
    ...

# foo

# bar
'''

TEST_FILE_2 = '''
"""
This type stub file was generated by pyright.
"""

import foo

"""
original docstring
"""

import bar

def foo():
    ...

# foo

# bar
'''

TEST_FILE_NORMALIZED_2 = '''
"""
original docstring
"""

import foo
import bar

def foo():
    ...

# foo

# bar
'''

TEST_FILE_3 = '''
"""
This type stub file was generated by pyright.
"""

def foo():
    ...

# foo

# bar
'''

TEST_FILE_NORMALIZED_3 = """
def foo():
    ...

# foo

# bar
"""


@pytest.mark.parametrize(
    ("inp", "expected"),
    [
        pytest.param(TEST_FILE_1, TEST_FILE_NORMALIZED_1, id="other-after-docstring"),
        pytest.param(TEST_FILE_2, TEST_FILE_NORMALIZED_2, id="import-after-docstring"),
        pytest.param(TEST_FILE_3, TEST_FILE_NORMALIZED_3, id="no-docstring-or-import"),
    ],
)
def test_normalize_pyright_out(inp: str, expected: str):
    normalized = normalize(inp.strip(), Config().validate())
    assert normalized == expected.strip() + "\n"
